# -*- coding: utf-8 -*-
"""Tamizhan skills 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZ-_NJis1Va8oQPd3CfmRg1KdSp0BBp4
"""

!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

import pandas as pd
df = pd.read_csv("financial_data.csv")
df.dropna(inplace=True)

display(df.head())

print(f"DataFrame shape before removing duplicates: {df.shape}")
df.drop_duplicates(inplace=True)
print(f"DataFrame shape after removing duplicates: {df.shape}")

print(df.info())

print(f"Average Income: ${df['person_income'].mean():.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['loan_amnt'], kde=True, bins=30)
plt.title('Distribution of Loan Amount')
plt.xlabel('Loan Amount')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['cb_person_cred_hist_length'], kde=True, bins=20)
plt.title('Distribution of Credit History Length')
plt.xlabel('Credit History Length (Years)')
plt.ylabel('Frequency')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the correlation matrix for numerical columns
correlation_matrix = df.select_dtypes(include=['number']).corr()

# Display correlations with 'loan_status'
print("Correlation with Loan Status:")
print(correlation_matrix['loan_status'].sort_values(ascending=False))

# Visualize the correlation matrix
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

plt.figure(figsize=(15, 5))

# Loan Percent Income vs Loan Status
plt.subplot(1, 3, 1)
sns.boxplot(x='loan_status', y='loan_percent_income', data=df)
plt.title('Loan % Income by Loan Status')
plt.xlabel('Loan Status (0: No Default, 1: Default)')
plt.ylabel('Loan % Income')

# Loan Interest Rate vs Loan Status
plt.subplot(1, 3, 2)
sns.boxplot(x='loan_status', y='loan_int_rate', data=df)
plt.title('Loan Interest Rate by Loan Status')
plt.xlabel('Loan Status (0: No Default, 1: Default)')
plt.ylabel('Loan Interest Rate')

# Person Income vs Loan Status
plt.subplot(1, 3, 3)
sns.boxplot(x='loan_status', y='person_income', data=df)
plt.title('Person Income by Loan Status')
plt.xlabel('Loan Status (0: No Default, 1: Default)')
plt.ylabel('Person Income')

plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 5))

# Loan Grade vs Loan Status
plt.subplot(1, 2, 1)
sns.countplot(x='loan_grade', hue='loan_status', data=df, palette='viridis')
plt.title('Loan Grade by Loan Status')
plt.xlabel('Loan Grade')
plt.ylabel('Count')
plt.legend(title='Loan Status')

# cb_person_default_on_file vs Loan Status
plt.subplot(1, 2, 2)
sns.countplot(x='cb_person_default_on_file', hue='loan_status', data=df, palette='magma')
plt.title('Credit Bureau Default by Loan Status')
plt.xlabel('Credit Bureau Default on File')
plt.ylabel('Count')
plt.legend(title='Loan Status')

plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define target variable
y = df['loan_status']

# Define features (X)
# Include numerical features that were identified as risk indicators or potentially relevant
numerical_features = ['loan_percent_income', 'loan_int_rate', 'person_income', 'loan_amnt', 'person_age', 'person_emp_length', 'cb_person_cred_hist_length']

# Include categorical features that were identified as risk indicators or potentially relevant
categorical_features = ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']

# Create a column transformer for one-hot encoding categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ])

# Create a pipeline with the preprocessor and Logistic Regression model
model_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                               ('classifier', LogisticRegression(random_state=42, solver='liblinear'))])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df[numerical_features + categorical_features], y, test_size=0.2, random_state=42)

# Train the model
model_pipeline.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

from sklearn.metrics import accuracy_score

predictions = model_pipeline.predict(X_test)
print(f"Model Accuracy: {accuracy_score(y_test, predictions):.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Risk distribution (Loan Status Distribution)
plt.figure(figsize=(7, 5))
sns.countplot(x='loan_status', data=df, palette='viridis')
plt.title('Distribution of Loan Status (Risk)')
plt.xlabel('Loan Status (0: No Default, 1: Default)')
plt.ylabel('Count')
plt.show()

# Income vs Loan amount
plt.figure(figsize=(10, 7))
sns.scatterplot(x='person_income', y='loan_amnt', hue='loan_status', data=df, alpha=0.6)
plt.title('Income vs Loan Amount by Loan Status')
plt.xlabel('Person Income')
plt.ylabel('Loan Amount')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# Credit score trends (Credit History Length distribution by Loan Status)
plt.figure(figsize=(10, 7))
sns.violinplot(x='loan_status', y='cb_person_cred_hist_length', data=df, palette='magma')
plt.title('Credit History Length by Loan Status')
plt.xlabel('Loan Status (0: No Default, 1: Default)')
plt.ylabel('Credit History Length (Years)')
plt.show()