# -*- coding: utf-8 -*-
"""tn task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRYQL-KEAW5P8eer8K1FEdQ0G8TDoscH
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("creditcard.csv")

df.head()

df.info()

df['Class'].value_counts()

sns.countplot(x='Class', data=df)
plt.title("Fraud vs Normal Transactions")
plt.show()

df.isnull().sum()

plt.figure(figsize=(8,5))
sns.histplot(df['Amount'], bins=50)
plt.title("Transaction Amount Distribution")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X = df.drop('Class', axis=1)
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Feature Correlation")
plt.show()

