# -*- coding: utf-8 -*-
"""tn tak 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OlMHVlteZmY7g8Iws_N-fWN2d7JESYXr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("mock_kaggle.csv")

print(df.head())
print(df.info())

# convert date column
df['data'] = pd.to_datetime(df['data'])

# sort by date
df = df.sort_values('data')

# check null values
print(df.isnull().sum())

df['year'] = df['data'].dt.year
df['month'] = df['data'].dt.month
df['day'] = df['data'].dt.day
df['day_of_week'] = df['data'].dt.dayofweek

df['lag_1'] = df['venda'].shift(1)
df['lag_7'] = df['venda'].shift(7)

df = df.dropna()

plt.figure(figsize=(12,5))
plt.plot(df['data'], df['venda'])
plt.title("Sales Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

sns.boxplot(x='month', y='venda', data=df)
plt.title("Monthly Sales Seasonality")
plt.show()

features = ['estoque','preco','month','day_of_week','lag_1','lag_7']

X = df[features]
y = df['venda']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

model = RandomForestRegressor(n_estimators=200)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))

print("MAE:", mae)
print("RMSE:", rmse)

plt.figure(figsize=(12,5))

plt.plot(y_test.values, label="Actual Sales")
plt.plot(predictions, label="Predicted Sales")

plt.legend()
plt.title("Sales Forecast vs Actual")
plt.show()