# -*- coding: utf-8 -*-
"""tn task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wv30m5pc9ULaFT2nw-rJdtI2QCe8tzFf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("E-commerce Customer Behavior - Sheet1.csv")

df.info()

df.describe()

df.isnull().sum()

df = df.dropna()

df.drop_duplicates(inplace=True)

plt.figure()
sns.histplot(df['Age'], bins=20)
plt.title("Customer Age Distribution")
plt.show()

sns.countplot(x="Gender", data=df)
plt.title("Gender Distribution")
plt.show()

sns.scatterplot(x="Total Spend", y="Items Purchased", data=df)
plt.title("Total spend vs Items Purchased")
plt.show()

from sklearn.cluster import KMeans

X = df[['Total Spend','Items Purchased']]

kmeans = KMeans(n_clusters=3)
df['Segment'] = kmeans.fit_predict(X)

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x='Total Spend',
    y='Items Purchased',
    hue='Segment'
)

plt.title("Customer Segmentation")
plt.show()

df.groupby('Segment')['Items Purchased'].mean()

