# -*- coding: utf-8 -*-
"""tn task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6hkQ8Y7IkyqwKy_rIyW90Q3hE4_jNnL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score